"""create all 7 tables per architecture.md

Revision ID: 4a44b14e95a4
Revises: 
Create Date: 2026-09-23 14:09:21.110307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a44b14e95a4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('entity_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('event_entities',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('event_id', 'entity_id'),
    sa.UniqueConstraint('event_id', 'entity_id', name='uq_event_entity')
    )
    op.create_table('event_entity_consensus',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('consensus_label', sa.String(), nullable=False),
    sa.Column('disagreement_score', sa.Float(), nullable=False),
    sa.Column('num_sources', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('event_id', 'entity_id'),
    sa.UniqueConstraint('event_id', 'entity_id', name='uq_event_entity_consensus')
    )
    op.create_table('event_entity_impact',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('impact_label', sa.Enum('positive', 'negative', 'neutral', 'mixed', name='impact_label_enum'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('event_id', 'entity_id', 'source_id')
    )
    op.create_table('event_post_map',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('event_id', 'post_id'),
    sa.UniqueConstraint('event_id', 'post_id', name='uq_event_post')
    )
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('representative_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('raw_posts',
    sa.Column('post_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('post_id'),
    sa.UniqueConstraint('content_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_posts')
    op.drop_table('events')
    op.drop_table('event_post_map')
    op.drop_table('event_entity_impact')
    op.drop_table('event_entity_consensus')
    op.drop_table('event_entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
