"""add cleaned_text_hash to raw_posts

Revision ID: 83289a9e010a
Revises: e7f7f56a0588
Create Date: 2026-09-23 19:05:23.503186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83289a9e010a'
down_revision: Union[str, None] = 'e7f7f56a0588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_posts', sa.Column('cleaned_text_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_raw_posts_cleaned_text_hash'), 'raw_posts', ['cleaned_text_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_posts_cleaned_text_hash'), table_name='raw_posts')
    op.drop_column('raw_posts', 'cleaned_text_hash')
    # ### end Alembic commands ###
