"""add fk constraints and indexes

Revision ID: e7f7f56a0588
Revises: 4a44b14e95a4
Create Date: 2026-09-23 18:57:38.537098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7f7f56a0588'
down_revision: Union[str, None] = '4a44b14e95a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_event_entities_event_id', 'event_entities', 'events', ['event_id'], ['event_id'], ondelete='CASCADE')
    op.create_foreign_key('fk_event_entities_entity_id', 'event_entities', 'entities', ['entity_id'], ['entity_id'], ondelete='CASCADE')
    op.create_foreign_key('fk_event_entity_consensus_event_id', 'event_entity_consensus', 'events', ['event_id'], ['event_id'], ondelete='CASCADE')
    op.create_foreign_key('fk_event_entity_consensus_entity_id', 'event_entity_consensus', 'entities', ['entity_id'], ['entity_id'], ondelete='CASCADE')
    op.create_foreign_key('fk_event_entity_impact_event_id', 'event_entity_impact', 'events', ['event_id'], ['event_id'], ondelete='CASCADE')
    op.create_foreign_key('fk_event_entity_impact_entity_id', 'event_entity_impact', 'entities', ['entity_id'], ['entity_id'], ondelete='CASCADE')
    op.create_foreign_key('fk_event_post_map_post_id', 'event_post_map', 'raw_posts', ['post_id'], ['post_id'], ondelete='CASCADE')
    op.create_foreign_key('fk_event_post_map_event_id', 'event_post_map', 'events', ['event_id'], ['event_id'], ondelete='CASCADE')
    op.create_index(op.f('ix_raw_posts_source_id'), 'raw_posts', ['source_id'], unique=False)
    op.create_index(op.f('ix_raw_posts_status'), 'raw_posts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_posts_status'), table_name='raw_posts')
    op.drop_index(op.f('ix_raw_posts_source_id'), table_name='raw_posts')
    op.drop_constraint('fk_event_post_map_event_id', 'event_post_map', type_='foreignkey')
    op.drop_constraint('fk_event_post_map_post_id', 'event_post_map', type_='foreignkey')
    op.drop_constraint('fk_event_entity_impact_entity_id', 'event_entity_impact', type_='foreignkey')
    op.drop_constraint('fk_event_entity_impact_event_id', 'event_entity_impact', type_='foreignkey')
    op.drop_constraint('fk_event_entity_consensus_entity_id', 'event_entity_consensus', type_='foreignkey')
    op.drop_constraint('fk_event_entity_consensus_event_id', 'event_entity_consensus', type_='foreignkey')
    op.drop_constraint('fk_event_entities_entity_id', 'event_entities', type_='foreignkey')
    op.drop_constraint('fk_event_entities_event_id', 'event_entities', type_='foreignkey')
    # ### end Alembic commands ###
